name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
        id: cache-node-modules
        with:
          node-version: '16'
      - run: npm i
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  generate-website:
    name: Generate website
    needs: node-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
        id: cache-node-modules
        with:
          node-version: '16'

      - name: Generate website
        id: build_website
        if: steps.cache-node-modules.outcome == 'success'
        run: npm run build
      
      - name: 🚀 Deploy to GitHub Pages 
        if: steps.build_website.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist